local M = {}
M.SCREEN_WIDTH = 1280
M.SCREEN_HEIGHT = 800
M.CELL_WIDTH = 32
M.CELL_HEIGHT = 32
M.CELL_COLUMNS = math.floor(M.SCREEN_WIDTH / M.CELL_WIDTH)
M.CELL_ROWS = math.floor(M.SCREEN_HEIGHT / M.CELL_HEIGHT)
return M